/** Auto-generated by create-fedi-app — do not edit manually. */
export interface IDemoRoute {
  href: string;
  title: string;
  description: string;
}

export const demoRoutes: IDemoRoute[] = [
  {
    href: '/demo/webln',
    title: 'WebLN Payments',
    description: 'Send and receive Lightning payments with WebLN.',
  },
  {
    href: '/demo/nostr',
    title: 'Nostr Identity',
    description: 'Sign in with NIP-07 and sign messages with your Nostr key.',
  },
  {
    href: '/demo/ecash',
    title: 'Ecash Balance',
    description: 'fediInternal mini-app discovery, list, and install prompts.',
  },
  {
    href: '/demo/payment-gated',
    title: 'Payment-Gated Content',
    description: 'Unlock articles and content after a Lightning payment.',
  },
  {
    href: '/demo/lnurl',
    title: 'LNURL',
    description: 'LNURL-pay, withdraw, and auth flows with QR codes.',
  },
  {
    href: '/demo/multispend',
    title: 'Multispend',
    description: 'Shared wallet proposals, votes, and approval flows.',
  },
  {
    href: '/demo/nostr-feed',
    title: 'Nostr Feed',
    description: 'Publish notes, browse a relay feed, and zap posts.',
  }
];
